<?php
/*require_once "/vendor/autoloader.php";
$security = new Security();
$loginMessage = $security->doLogin();*/
?>
<!DOCTYPE html>
<head>
<meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
<title>Login</title>
<link rel="stylesheet" type="text/css" href="form/view.css" media="all">
<script type="text/javascript" src="form/view.js"></script>

</head>
<body id="main_body" >
<header>
        <div class="container-fluid">
            <div class="row">
                <nav class="navbar navbar-expand-sm navbar-dark">
                    <a class="navbar-brand col-1" href="login.php">
                        <img src="assets/img/image-removebg-preview.png" alt="Avatar Logo" style="width:50px;">
                    </a>
                    <h2 class="col-10 text-center">La casa del electrodomestico</h2>
                </nav>
            </div>
        </div>
    </header>
	<img id="top" src="form/top.png" alt="">
	<div id="form_container">

		<h1><a>Login</a></h1>
		<form class="appnitro" method="post" action=""><div class="form_description">
			<h2>Login</h2>
			<h4><?=$loginMessage?></h4>
			<p></p>
		</div>
			<ul >

					<li id="li_1" >
		<label class="description" for="userName">User Name</label>
		<div>
			<input name="userName" class="element text medium" type="text" maxlength="255" value=""/>
		</div>
		</li>		<li id="li_2" >
		<label class="description" for="userPassword">User Password </label>
		<div>
			<input name="userPassword" class="element text medium" type="password" maxlength="255" value=""/>
		</div>
		</li>

					<li class="buttons">

				<input id="saveForm" class="button_text" type="submit" name="submit" value="Log In" />
		</li>
			</ul>
		</form>
		<div id="footer">
			Generated by <a href="http://www.floridauniversitaria.es">DAW1</a>
		</div>
	</div>
	<img id="bottom" src="form/bottom.png" alt="">
	</body>
	<footer>
        <div class="container-fluid" style="background-color: #4D6E9B; margin-top:100px;position:fixed;">
            <div class="row">
				<div class="navbar navbar-fixed-bottom">
                <div class="col-12 text-center">
				<p>Derechos reservados &copy; 2023</p>
                <p><a href="assets/privacity/privacityPolitic.pdf" target="_blank">Politica de privacidad</a></p>
                </div>
				</div>
            </div>
        </div>
    </footer>
</html>
